# Generated by Django 2.1.7 on 2019-02-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190217_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='absent',
            name='send_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
