# Generated by Django 2.1.7 on 2020-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='line_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
