# Generated by Django 2.1.7 on 2020-02-01 16:56

from django.db import migrations
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_room_line_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='classroom',
            field=web.models.IntegerRangeField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room',
            field=web.models.IntegerRangeField(blank=True, default=1, null=True),
        ),
    ]
